# Example configuration file for survey mailer
#
# This file is the base for all configuration settings.
# 
# Note: SMTP delivery is setup to use mailcatcher(see https://mailcatcher.me/)
# defaults in the test and development environments.
# 
# Usage:
#
# Copy this file from `config/config.defaults.yml` to `config/config.yml`
#

test:
    smtp_host: localhost
    smtp_port: 1025
    smtp_user: ''
    smtp_password: ''

    text_template: templates/hut_survey_email.txt.erb
    html_template: templates/hut_survey_email.html.erb

    # Delay in days. When 2, send emails for visits ending 2 days ago
    email_delay: 2

development:
    smtp_host: localhost
    smtp_port: 1025
    smtp_user: ''
    smtp_password: ''

    text_template: templates/hut_survey_email.txt.erb
    html_template: templates/hut_survey_email.html.erb

    # Delay in days. When 2, send emails for visits ending 2 days ago
    email_delay: 2

production:
