# Example configuration file for survey mailer
#
# This file is the base for all configuration settings.
# 
# Note: SMTP delivery is setup to use mailcatcher(see https://mailcatcher.me/)
# defaults in the test and development environments.
# 
# Usage:
#
# Copy this file from `config/config.defaults.yml` to `config/config.yml`
#

test:
    smtp:
        host: localhost
        port: 1025
        user: ''
        password: ''

    sending_options:
        - delay: 2
          template: 
              html: templates/hut_survey_email.html.erb
              text: templates/hut_survey_email.txt.erb
        - delay: -5
          template: 
              html: templates/reservation_reminder_email.html.erb
              text: templates/reservation_reminder_email.txt.erb

development:
    smtp:
        host: localhost
        port: 1025
        user: ''
        password: ''

    sending_options:
        - delay: 2
          template: 
              html: templates/hut_survey_email.html.erb
              text: templates/hut_survey_email.txt.erb
        - delay: -5
          template: 
              html: templates/reservation_reminder_email.html.erb
              text: templates/reservation_reminder_email.txt.erb

production:

